import type { Metadata } from "next";
import "./globals.css";
import { FaMapSigns } from "react-icons/fa";
import { CiBookmark } from "react-icons/ci";
import { IoIosAddCircleOutline } from "react-icons/io";
import { auth } from '@/auth';
import { LogoutButton } from "@/components/Logout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {!!session ? <LogoutButton /> : ''}
        {children}
        {!!session ? <footer className="flex justify-around fixed bottom-0 w-screen py-4">
          <FaMapSigns />
          <CiBookmark />
          <IoIosAddCircleOutline />
        </footer> : ""}
      </body>
    </html>
  );
}
